### ISSUE TITLE
TypeError: any is not a recognized Joi type

### ISSUE THREAD

**Issue by MarkHerhold** [Twipped/joi-to-swagger#12]
Hey there, neat project!

I wanted to try this out but I ran into a snag trying to run it against a simple Joi schema. Am I doing something wrong?

```js
var j2s = require('joi-to-swagger'); // latest, 1.2.0
const Joi = require('joi'); // latest, v13.0.2
const schema = Joi.object().keys({
  id: Joi.any().forbidden(), 
  key: Joi.string()
});

j2s(schema); // boom!
```

```
TypeError: any is not a recognized Joi type.
    at parse (/Users/Mark/test/node_modules/joi-to-swagger/index.js:37:9)
    at children.forEach (/Users/Mark/test/node_modules/joi-to-swagger/index.js:292:15)
    at Array.forEach (<anonymous>)
    at Object.object (/Users/Mark/test/node_modules/joi-to-swagger/index.js:290:12)
    at parse (/Users/Mark/test/node_modules/joi-to-swagger/index.js:35:38)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
```

**Comment by Twipped** [comment]
Swagger only allows for one data type per property, so support for `joi.any()` wasn't implementable. I'm not actually sure swagger has a way to define a forbidden property, short of omitting it and adding `additionalProperties: false` to the object definition.

If you can provide an example swagger output that would fit that that schema, then I can look into adding it.

**Comment by MarkHerhold** [comment]
Good point about swagger output, but I think that throwing an unrecoverable error is probably not the best way to handle this as one field ruins the bunch.

My initial thought is that `any` could be represented as `binary` or `any` types could be left out/suppressed by default.

Would you accept a PR to suppress the `any` type from showing up in the schema and not throw an error (perhaps log a warning)?

**Comment by MarkHerhold** [comment]
A second thought: Joi allows users to provide new types via [`Joi.extend()`](https://github.com/hapijs/joi/blob/v13.0.2/API.md#extendextension), so I see the potential for a lot of users to run into this same type of issue. Perhaps another approach would to allow users to provide "type resolvers" (think plugin) to `j2s` that way we push undefined behavior down to the user level. Thoughts?

**Comment by Twipped** [comment]
The plugin idea makes the most sense to me. I'll mull it over and see if I can come up with an api I like.

I would accept a PR to ignore `any` and not trigger an error, you can probably do it by just adding `any: () => false` to the `parseAsType` collection. It definitely should at least issue a warning (maybe via [`util.deprecate`](https://nodejs.org/docs/latest-v8.x/api/util.html#util_util_deprecate_function_string)) if it's going to ignore the entry. Otherwise people wouldn't understand (and possibly not even notice) why it's absent.

**Comment by Makpoc** [comment]
Sorry for the sort-of-necro-bump, but didn't want to open separate issue about topic, discussed here.

I looked around but didn't see any PRs related to the Joi.extend() issue, mentioned above. Was any progress made on that?

**Comment by Twipped** [comment]
Not really. The way I've addressed it in my own projects is to just explicitly define the swagger using the `meta()` override.
