### ISSUE TITLE
question: is there a library that goes in the opposite direction? swagger-to-joi?

### ISSUE THREAD

**Issue by paul42** [Twipped/joi-to-swagger#3]
Just wondering - I have a project idea where I use editor.swagger.io as my scratchpad, create routes in there, and then write handlers in my code base, and parse that swagger.json into routes/models/etc. 

Thanks in advance

**Comment by Twipped** [comment]
None that I'm aware of or could find searching npm. It would probably be pretty easy to write, however, since swagger is significantly less flexible than joi is.

**Comment by panKt** [comment]
Are there any updates on this?

**Comment by Twipped** [comment]
If you're asking if I'm writing one, the answer is no. I have no need for it.
