### ISSUE TITLE
Feature: Include examples with any.example()

### ISSUE THREAD

**Issue by Floby** [Twipped/joi-to-swagger#34]
This is a feature request. =)

Joi offers to define some examples for any value.
Swagger allows kind of the [same](https://swagger.io/docs/specification/describing-request-body/) [thing](https://swagger.io/docs/specification/2-0/adding-examples/).

It would be nice to be able to define examples directly in Joi and have them show up in the generated swagger defintion.

**Comment by Twipped** [comment]
Sorry, I just saw the part about being able to define an example for a definition block. Ok, this is something we could implement.
