### ISSUE TITLE
Does this library work with Joi date extensions?

### ISSUE THREAD

**Issue by andrewryan1906** [Twipped/joi-to-swagger#35]
I'm trying to use Joi date extensions and am getting a weird validation error:

```
Error: {
  "format" [1]: -- missing --
}

[1] "format" is required

ValidationError: {\n  \u001b[41m\"format\"\u001b[0m\u001b[31m [1]: -- missing --\u001b[0m\n}\n\u001b[31m\n[1] \"format\" is required\u001b[0m\n    at Object.exports.process (D:\\rhythm\\rolodex-contacts\\node_modules\\joi\\lib\\errors.js:196:19)\n
```

How do I make this work?

Thanks!
Andrew

**Comment by Twipped** [comment]
I'm sorry, I'm missing context here. Are you saying that the swagger that the library is producing isn't passing validation? Can you provide an example of the Joi that is being evaluated?

**Comment by andrewryan1906** [comment]
I've resolved this.

My goal was to accept a date in the ISO 8601 UTC format.  I thought I needed to use joi date extensions to do this; it turns out I only needed:

``` Joi.date().iso()
```

That did the trigger. I also was able to force the Swagger to output "date" instead of "date-time" using the meta override.
