### ISSUE TITLE
Convert Joi label to Swagger title

### ISSUE THREAD

**Issue by jimcatts** [Twipped/joi-to-swagger#36]
Hello! I am currently setting the Swagger title value from my Joi using the .meta function like:

.meta({swagger: {title: 'Name'}})

I would rather be able to use the Joi label function like:

.label('Name') 

and have it automatically mapped to the title in Swagger. If the new feature is acceptable, I have a PR ready to submit.

Love the project! Thank you!!
Jim

**Comment by Twipped** [comment]
That sounds like a great idea, go right ahead.

**Comment by jimcatts** [comment]
Thank you!
