### ISSUE TITLE
Error when a property has a forbidden flag

### ISSUE THREAD

**Issue by jrom93** [Twipped/joi-to-swagger#41]
Hi. I have a Joi schema which has forbidden flag for one of its property.  I get this error:
"Cannot create property 'description' on boolean 'false'"
when trying to convert it to a swagger object.

line 44 of index.js (3.0.0):
swagger = parseAsType[schema._type](schema, existingComponents, components);
sets the swagger object to false instead of returning.
Code afterwards treats it like an object and it fails because it is boolean type.

**Comment by Twipped** [comment]
Sorry for taking so long to get back to this, I just saw the notification for it. Can you provide a Joi example that reproduces this?

**Comment by jrom93** [comment]
`const sample = Joi.object().keys({
    "id": Joi.string()
        .description("user id")
        .forbidden(),

    "name": Joi.string()
});

const { swagger, definitions } = joiToSwagger(sample);
`

**Comment by jrom93** [comment]
const sample = Joi.object().keys({
    "id": Joi.string()
        .description("user id")
        .forbidden(),

    "name": Joi.string()
});

const { swagger, definitions } = joiToSwagger(sample);

**Comment by Twipped** [comment]
Ok, I've fixed this on master branch. The problem is that swagger doesn't actually have a provision for identifying something that doesn't belong. If it isn't in the swagger, it doesn't belong, so J2S simply omits the property from the schema by returning false for that property.
