### ISSUE TITLE
Swagger OpenAPI 3.0 now supports alternatives

### ISSUE THREAD

**Issue by pke** [Twipped/joi-to-swagger#44]
Currently `joi.alternatives()` only selects the first item for the swagger doc.
However OpenAPI now supports multiple inputs, so joi-to-swagger could get rid of that limitation. What do you think? Start supporting OpenAPI 3.0?

**Comment by Twipped** [comment]
I'd welcome a PR to add it.

**Comment by pke** [comment]
On its way :)
Should we trigger the new path by an option, lets say one can define the OpenAPI version to use?

**Comment by pke** [comment]
Nah, I agree why maintain backward comparability for an old documentation standard?

**Comment by igor-sky** [comment]
Hi guys, any updates on this?

**Comment by Mairu** [comment]
Well, there was no PR provided. So no updates as you can see.

**Comment by Mairu** [comment]
Support for that was added in version 4.
