### ISSUE TITLE
Update joi dependency to use @hapi/joi

### ISSUE THREAD

**Issue by FredrikJLindberg** [Twipped/joi-to-swagger#58]
Currently using https://www.npmjs.com/package/joi dependency but as it's depracated it would be nice if the dependency could be updated to use https://www.npmjs.com/package/hapi-joi-to-swagger instead.

**Comment by Mairu** [comment]
You linked a fork of this package.
There has already been some work done to use @hapi/joi. (https://github.com/Twipped/joi-to-swagger/tree/joi_16)
But they did a major rewrite in version 16 that needed some more work than just using a different package name.
I will continue when I find some time.

See also: https://github.com/Twipped/joi-to-swagger/pull/56

**Comment by FredrikJLindberg** [comment]
Ah, sorry! Had both tabs open and managed to link the fork instead of the @hapi/joi package (https://www.npmjs.com/package/@hapi/joi).

Seeing how helpful this package of yours is I'll probably keep using the depracated joi version for the time being, but would ofc want to change asap.

Cheers for the quick reply and for the great tool.

**Comment by renatoargh** [comment]
Hey guys, first of all; super thanks for the work on this library! I really like it! Second, do we have any updates on this issue? The lib seems untouched for a while! :)

**Comment by Mairu** [comment]
There is https://github.com/Twipped/joi-to-swagger/pull/62 open, it looks good. When I find the time, I will create a new release from it.
Sadly my time is very limited atm, but it should really not take longer than 2 weeks.

**Comment by Mairu** [comment]
Version 4.0.0 released
