### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by damiancipolat** [Twipped/joi-to-swagger#63]
Hi, I'm looking for more examples to use this module. Could you add some complete example of how to integrate this module with a swagger file or with some apirest with expressjs?

**Comment by Mairu** [comment]
This library helps to create openapi v3 schemas from joi object validation definitions.
Either you have another library to create the rest of your openapi specification or you have to create it yourself. You should read into the [openapi specification](https://swagger.io/docs/specification/about/). 

The 2nd parameter refers to the https://swagger.io/docs/specification/components/ when references can be reused.

**Comment by damiancipolat** [comment]
OK I understand but I can't find an executable example from this library, could you upload at least one that shows an input / output? of the schemas.

**Comment by Mairu** [comment]
It is the first thing in the readme :D

(The output is the swagger of the return object).

**Comment by damiancipolat** [comment]
ok, thanks!

**Comment by wll8** [comment]
@Twipped  @Mairu  
Can you add an example with more parameters? It is very helpful for those who are not familiar with openApi but want to use it with this library.

**Comment by Mairu** [comment]
@wll8 Well there is no need for more parameters.
How you define your joi schema, depends on your requirements.

And how you create the OpenAPI documents depends on the library which you should use for creating and serving the OpenAPI specification.

So if are you using anything already and don't know how to put it together, then please list them. Or at least list the libraries you are using to give some hints on how to help you.
