### ISSUE TITLE
regeneratorRuntime - error

### ISSUE THREAD

**Issue by damiancipolat** [Twipped/joi-to-swagger#64]
Hi I'm receiving this error. Is a bug, can you help me?

C:\Users\54116\Desktop\Proyectos\node_swagger\express_joi_swagger\node_modules\j2s\dist\index.js:6
    var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(ctx, instances, funcs) {
                                 ^

ReferenceError: regeneratorRuntime is not defined
    at C:\Users\54116\Desktop\Proyectos\node_swagger\express_joi_swagger\node_modules\j2s\dist\inde
x.js:6:34
    at Object.<anonymous> (C:\Users\54116\Desktop\Proyectos\node_swagger\express_joi_swagger\node_m
odules\j2s\dist\index.js:48:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\54116\Desktop\Proyectos\node_swagger\express_joi_swagger\node_m
odules\j2s\index.js:1:18)

----------------------------------
Running this code:
const joi 		 = require('@hapi/joi');
const j2s 		 = require('j2s');

const mySchema = joi.object().keys({
  id:      joi.number().integer().positive().required(),
  name:    joi.string(),
  email:   joi.string().email().required(),
  created: joi.date().allow(null),
  active:  joi.boolean().default(true),
});

const { swagger, components } = j2s(mySchema);

console.log(swagger,components);

---------------------------------------
NODEJS VERSION: v10.16.3

Package.json:
{
  "name": "express_joi_swagger",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@hapi/joi": "^17.1.1",
    "j2s": "^2.0.6"
  }
}

**Comment by Mairu** [comment]
This error originates from j2s which is not this library?

It looks like a babel error: https://github.com/babel/babel/issues/9849

This project does not use babel, so it cannot be the source of the problem.

**Comment by damiancipolat** [comment]
yeah! you are rigth. I'm importing other module, thanks, it's working now, but I'm a little confused of how to use the classname to make the ref between the schema and the joi object?

**Comment by Mairu** [comment]
Currently, you can look into the tests as some kind of documentation.
That is the only way but looking into the code or trying it out.
