### ISSUE TITLE
[FEATURE] Support for schema.tailor and schema.alter

### ISSUE THREAD

**Issue by Aposhian** [Twipped/joi-to-swagger#66]
In Joi, you can create subtle variants of a schema using [alter and tailor](https://hapi.dev/module/joi/api/?v=17.1.1#anyaltertargets). This is not reflected in the `joi-to-swagger` conversion.

For example,

```js
const MySchema = Joi.object({
  property1: Joi.string(),
  property2: Joi.string().alter({
    special: schema => schema.strip()
  })
})

const SpecialSchema = MySchema.tailor('special')
```

still produces

```
"SpecialSchema": {
  "type": "object",
  "properties": {
    "property1": {
      "type": "string"
    },
    "property2": {
      "type": "string"
    }
  }
}

```

**Comment by Mairu** [comment]
Any PRs are welcome ;)

**Comment by Aposhian** [comment]
Upon further investigation, I was mistaken in stating that `alter` and `tailor` were being ignored. I was unclear about the behavior of `strip()`.

I actually think that `joi-to-swagger` is handling this correctly, since [`strip()` removes the property *after* validation.](https://github.com/hapijs/joi/blob/master/API.md#anystripenabled)

`forbidden()` successfully removes the property in the resulting swagger schema, even inside an alter.

So now my question is how to basically strip without validation, but without explicitly forbidding the property. But since that is more of a Joi question, I'm going to close this.

```js
const MySchema = Joi.object({
  myProperty: Joi.string().alter({
    thisRemovesProperty: schema => schema.forbidden(),
    thisKeepsProperty: schema => schema.strip()
  })
})
```
