### ISSUE TITLE
joi is leaving the @hapi organization and moving back to 'joi'

### ISSUE THREAD

**Issue by mparikh31** [Twipped/joi-to-swagger#69]
joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411). With this, can this library be updated to use latest joi again - https://www.npmjs.com/package/joi, as @hapi/joi is now a deprecated npm package. 

Thanks!

**Comment by Mairu** [comment]
Published a new version 5.0.0

**Comment by mparikh31** [comment]
This is great. Many Thanks @Mairu
