### ISSUE TITLE
False default values for boolean not passing

### ISSUE THREAD

**Issue by nelsongomes** [Twipped/joi-to-swagger#71]
**@Mairu please copy this code, this is fix to allow to pass false boolean in defaultValue.**

**Code changes**:
	const defaultValue = get(schema, '_flags.default');
	if ((defaultValue || typeof defaultValue === 'boolean') && typeof defaultValue !== 'function') {
		swagger.default = defaultValue;
	}

**test code**:
	simpleTest(
		'boolean',
		joi.boolean().default(false),
		{
			default: false,
			type: 'boolean',
		},
	);

**tried to open a PR, but was not possible.**

**Comment by Mairu** [comment]
I applied the changes and released a new version 5.1.0.
Thx for the fix.

**Comment by nelsongomes** [comment]
Thank you

A sábado, 17/10/2020, 17:13, Sebastian Große <notifications@github.com>
escreveu:
