### ISSUE TITLE
Description feature

### ISSUE THREAD

**Issue by ryok90** [Twipped/joi-to-swagger#81]
Hello!
I've come across your lib and it has been great so far.
I was wondering if it is possible to add one feature though.
Joi has a description feature which would come in handy to specify some fields on Swagger.

Could this be implemented or are you accepting pull requests?

**Comment by Mairu** [comment]
Hi, PRs are always welcome.

I thought descriptions are already supported.
https://github.com/Twipped/joi-to-swagger/blob/master/index.js#L361

But there is no test for it, so perhaps that is wrong and not working.

**Comment by ryok90** [comment]
Hmm, I'll give it a go in the next few days.

Thank you for the quick response.

**Comment by ryok90** [comment]
I'm sorry mate. Apparently I had configured it wrong. It is working as intended.

Thank you!
